# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-06 09:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bustrackerapp', '0002_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusStop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route', models.CharField(max_length=200)),
                ('location_lat', models.DecimalField(decimal_places=4, max_digits=8)),
                ('location_lon', models.DecimalField(decimal_places=4, max_digits=8)),
                ('stop_name', models.CharField(max_length=200)),
                ('seq', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='bus',
            old_name='bus_location',
            new_name='last_stop',
        ),
        migrations.AddField(
            model_name='bus',
            name='bus_location_lat',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bus',
            name='bus_location_lon',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bus',
            name='next_stop',
            field=models.CharField(default='none', max_length=200),
            preserve_default=False,
        ),
    ]
