# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-06 10:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bustrackerapp', '0003_auto_20180406_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='bus_location_lat',
            field=models.DecimalField(decimal_places=6, max_digits=8),
        ),
        migrations.AlterField(
            model_name='bus',
            name='bus_location_lon',
            field=models.DecimalField(decimal_places=6, max_digits=8),
        ),
        migrations.AlterField(
            model_name='busstop',
            name='location_lat',
            field=models.DecimalField(decimal_places=6, max_digits=8),
        ),
        migrations.AlterField(
            model_name='busstop',
            name='location_lon',
            field=models.DecimalField(decimal_places=6, max_digits=8),
        ),
    ]
