# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-06 10:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bustrackerapp', '0004_auto_20180406_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='busstop',
            name='reverse',
            field=models.BooleanField(default=False),
        ),
    ]
