# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-07 12:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bustrackerapp', '0007_bus_currseq'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='numTravellers',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='startStation',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='stopStation',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
    ]
